[package]
name = "rt_bevy"
version = "0.1.0"
edition = "2021"
authors = ["Simon Sommer <creatorsisohd@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.dist]
inherits = "release"
lto = "fat"

[dependencies.bevy]
version = "0.10"
default-features = false
features = [
	"wayland",
	"bevy_winit",
	"bevy_render",
	"bevy_core_pipeline",
	"bevy_pbr",
]

[dependencies]
bevy_asset_loader = { version = "0.15" }
indoc = "2.0"
rand = { version = "0.8" }
